const SET_LOGGED_USER = "SET_LOGGED_USER"
const SET_INITIAL_STATE = 'SET_INITIAL_STATE';
const SET_HISTORY = 'SET_HISTORY';

export default {
    SET_LOGGED_USER,
    SET_INITIAL_STATE,
    SET_HISTORY
}
